### PR TITLE
Use a non-ambiguous date format

### PR DESCRIPTION
**Pull request by DarthGandalf**

### CODE REVIEW

**Comment by ymjing** [comment]
Trivial. Won't fix.

**Comment by DarthGandalf** [comment]
Yes, trivial. How is that a good reason to not fix?
https://xkcd.com/1179/

вт, 9 мар. 2021 г. в 17:00, Yiming Jing <notifications@github.com>:

**Comment by ymjing** [comment]
OK fine.

**Comment by DarthGandalf** [comment]
Yep, that format also works. Thanks!

вт, 9 мар. 2021 г. в 17:18, Yiming Jing <notifications@github.com>:

**Pull request closed without merging**
